objeto = input('Digite algo e o sistema irá verificar a qual tipo primitivo pertence e as informações: ')
print('O seu tipo primitivo é:',type(objeto))
print('Algo foi digitado', objeto.isidentifier())
print('{} é um número?'.format(objeto), objeto.isnumeric())
print('{} é alfabético?'.format(objeto), objeto.isalpha())
print('{} é alfanumérico?'.format(objeto), objeto.isalnum())
print('{} está em maiúsculo?'.format(objeto), objeto.isupper())
print('{} está em minúsculo?'.format(objeto),objeto.islower())
print('{} está capitalizada?'.format(objeto),objeto.istitle())
print('apenas espaços?',objeto.isspace())
